
/**
* Constants
*/
const Constants = {
    // changeAsteroidId
    CHANGE_ASTEROID_ID:"CHANGE_ASTEROID_ID",
    UPDATE_ASTEROID_INFO:"UPDATE_ASTEROID_INFO",
    INIT_ASTEROID_INFO:"INIT_ASTEROID_INFO",
    SHOW_LOADING:"SHOW_LOADING",
    HIDE_LOADING:"HIDE_LOADING",
    INFO_API_SUCCESS:"INFO_API_SUCCESS",
    INFO_API_ERROR:"INFO_API_ERROR",
    RANDOM_API_SUCCESS:"RANDOM_API_SUCCESS",
    RANDOM_API_ERROR:"RANDOM_API_ERROR",
    BACK_BUTTON_FOR_INFO:"BACK_BUTTON_FOR_INFO"
};
export default Constants;
